eticaret/Models/ProductImages.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eticaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImages
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public string ImagePath { get; set; }
    
        public virtual Products Products { get; set; }
    }
}

eticaret/Models/SoldProducts.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eticaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoldProducts
    {
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> BagID { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Products Products { get; set; }
        public virtual Bags Bags { get; set; }
    }
}

eticaret/Areas/Admin/Controllers/ManagementController.cs
using eticaret.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace eticaret.Areas.Admin.Controllers
{
    [ShopAuthorize]
    public class ManagementController : Controller
    {
        eTicaretDBEntities db = new eTicaretDBEntities();


        public ActionResult LeftSideBar()
        {
            return View();
        }


        // Tüm aktif ürünleri getir
        public ActionResult Index(int? pageNo)
        {
            int _pageNo = pageNo ?? 1;
            string arama = Request.QueryString["arama"];
            var productList = new Object();
            if (!string.IsNullOrWhiteSpace(arama))
            {
                productList = db.Products.Where(x => x.Name.Contains(arama) || x.Description.Contains(arama) || x.ExtraDescription.Contains(arama)).OrderBy(x => x.Name).ToPagedList<Products>(_pageNo, 10);

            }
            else
            {
                productList = db.Products.OrderBy(x => x.Name).ToPagedList<Products>(_pageNo, 10);
            }
            return View(productList);
        }

        //Ürünü pasife al
        [HttpGet]
        public ActionResult RemoveProduct(int? id)
        {
            try
            {
                Products pr = db.Products.FirstOrDefault(x => x.ID == id);

                if (pr != null)
                {
                    pr.Status = false;
                    db.SaveChanges();
                    Log.ProductRemoveLog(pr.ID);
                }
            }
            catch (Exception)
            {
                return Redirect("/Admin/management/index?Status=DeleteFailed");
            }

            return Redirect("/Admin/management/index?Status=DeleteSuccess");
        }

        //Ürünü güncelle -get
        [HttpGet]
        public ActionResult EditProduct(int? id)
        {
            Products pr = db.Products.FirstOrDefault(x => x.ID == id);
            if (pr == null)
            {
                return HttpNotFound();
            }
            return View(pr);
        }

        //Ürünü güncelle -post
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditProduct(int? id, Products p)
        {
            Products pr = db.Products.FirstOrDefault(x => x.ID == id);
            if (pr == null)
            {
                return HttpNotFound();
            }
            else
            {
                pr.Name = p.Name;
                pr.Description = p.Description;
                pr.ExtraDescription = p.ExtraDescription;
                pr.UnitsInStock = p.UnitsInStock;
                pr.Price = p.Price;
                pr.Status = p.Status;


                #region Image Upload
                if (Request.Files.Count > 0)
                {
                    #region Old Images - Delete
                    if (System.IO.File.Exists(Server.MapPath(pr.Photo)))
                    {
                        System.IO.File.Delete(Server.MapPath(pr.Photo));
                    }
                    if (System.IO.File.Exists(Server.MapPath(pr.Photo.Replace("uploads/ProductMasterImages/OS", "uploads/ProductMasterImages/L"))))
                    {
                        System.IO.File.Delete(Server.MapPath(pr.Photo.Replace("uploads/ProductMasterImages/OS", "uploads/ProductMasterImages/L")));
                    }
                    if (System.IO.File.Exists(Server.MapPath(pr.Photo.Replace("uploads/ProductMasterImages/OS", "uploads/ProductMasterImages/S"))))
                    {
                        System.IO.File.Delete(Server.MapPath(pr.Photo.Replace("uploads/ProductMasterImages/OS", "uploads/ProductMasterImages/S")));
                    }
                    #endregion

                    HttpPostedFileBase file = Request.Files[0];

                    WebImage img = new WebImage(file.InputStream);
                    FileInfo fotoinfo = new FileInfo(file.FileName);

                    Random rnd = new Random();
                    int random = rnd.Next(1000, 9999);
                    string filename = file.FileName.Remove(file.FileName.Length - fotoinfo.Extension.Length, fotoinfo.Extension.Length);
                    string imgname = DateTime.UtcNow.Month.ToString() + DateTime.UtcNow.Day.ToString() + "_" + pr.ID + "_" + filename + "_" + random;
                    string newfoto = imgname + fotoinfo.Extension;
                    img.Save("~/uploads/ProductMasterImages/OS/" + newfoto);
                    Helpers.ImageResize("uploads/ProductMasterImages/OS", "uploads/ProductMasterImages/L", newfoto, 1024, 768);
                    Helpers.ImageResize("uploads/ProductMasterImages/OS", "uploads/ProductMasterImages/S", newfoto, 200, 155);

                    pr.Photo = "/uploads/ProductMasterImages/OS/" + newfoto;
                }
                #endregion


                db.SaveChanges();
                Log.ProductUpdateLog(pr.ID);
            }
            return View(pr);
        }

        //Ürün resimlerini bas
        public ActionResult ProductImages(int? id)
        {
            Products pr = db.Products.FirstOrDefault(x => x.ID == id);
            if (pr == null)
            {
                return HttpNotFound();
            }

            return View(pr.ProductImages.ToList());
        }

        //Ürün resmi yükle
        [HttpPost]
        public ActionResult ImagesUpload()
        {
            try
            {
                string ProductID = Request.QueryString["ID"];
                if (String.IsNullOrWhiteSpace(ProductID)) return Redirect("/Admin/Admin");

                if (Request.Files.Count > 0)
                {
                    HttpPostedFileBase file = Request.Files[0];
                    ProductImages photo = new ProductImages();
                    photo.ProductID = int.Parse(ProductID);

                    WebImage img = new WebImage(file.InputStream);
                    FileInfo fotoinfo = new FileInfo(file.FileName);

                    Random rnd = new Random();
                    int random = rnd.Next(1000, 9999);
                    string filename = file.FileName.Remove(file.FileName.Length - fotoinfo.Extension.Length, fotoinfo.Extension.Length);
                    string imgname = DateTime.UtcNow.Month.ToString() + DateTime.UtcNow.Day.ToString() + "_" + photo.ProductID + "_" + filename + "_" + random;
                    string newfoto = imgname + fotoinfo.Extension;
                    img.Save("~/uploads/Products/OS/" + newfoto);
                    Helpers.ImageResize("uploads/Products/OS", "uploads/Products/L", newfoto, 1024, 768);
                    Helpers.ImageResize("uploads/Products/OS", "uploads/Products/S", newfoto, 200, 155);

                    photo.ImagePath = "/uploads/Products/OS/" + newfoto;
                    db.ProductImages.Add(photo);
                    db.SaveChanges();
                }
            }
            catch (Exception)
            {
                return Json("-1", JsonRequestBehavior.AllowGet);
            }

            return Json("1", JsonRequestBehavior.AllowGet);
        }


        //Ürün resmi sil
        [HttpPost]
        public ActionResult DeleteProductImage(int? id)
        {
            try
            {
                ProductImages img = db.ProductImages.Find(id);

                if (System.IO.File.Exists(Server.MapPath(img.ImagePath)))
                {
                    System.IO.File.Delete(Server.MapPath(img.ImagePath));
                }
                if (System.IO.File.Exists(Server.MapPath(img.ImagePath.Replace("uploads/Products/OS", "uploads/Products/L"))))
                {
                    System.IO.File.Delete(Server.MapPath(img.ImagePath.Replace("uploads/Products/OS", "uploads/Products/L")));
                }
                if (System.IO.File.Exists(Server.MapPath(img.ImagePath.Replace("uploads/Products/OS", "uploads/Products/S"))))
                {
                    System.IO.File.Delete(Server.MapPath(img.ImagePath.Replace("uploads/Products/OS", "uploads/Products/S")));
                }
                db.ProductImages.Remove(img);
                db.SaveChanges();
            }
            catch (Exception)
            {
                return Json("-1", JsonRequestBehavior.AllowGet);
            }
            return Json("1", JsonRequestBehavior.AllowGet);
        }

        //Tüm Pasif ürünleri getir ve güncelle
        public ActionResult SoftDeletedProducts(int? pageNo)
        {
            int _pageNo = pageNo ?? 1;
            var productList = db.Products.Where(x => x.Status == false).OrderBy(x => x.Name).ToPagedList<Products>(_pageNo, 10);

            return View(productList);
        }


        //Satışları listele
        public ActionResult SoldProducts(int? pageNo)
        {
            int _pageNo = pageNo ?? 1;

            var soldProductList = db.SoldProducts.OrderBy(x => x.ID).ToPagedList<SoldProducts>(_pageNo, 10);

            return View(soldProductList);
        }


        //Admin hesaplarını göster
        [HttpGet]
        public ActionResult Accounts()
        {
            List<Admins> adminList = db.Admins.ToList();

            return View(adminList);
        }


        //Admin hesaplarını güncelle -get
        public ActionResult EditAdmin(int? id)
        {
            Admins admin = db.Admins.FirstOrDefault(x => x.ID == id);

            return View(admin);
        }

        //Admin hesaplarını güncelle -post
        [HttpPost]
        public ActionResult EditAdmin(int? id, Admins a)
        {
            Admins admin = db.Admins.Where(x => x.ID == id).SingleOrDefault();
            if (admin == null)
            {
                return HttpNotFound();
            }
            else
            {
                admin.Name = a.Name;
                admin.Lastname = a.Lastname;
                admin.Email = a.Email;
                admin.Status = a.Status;

eticaret/Areas/Admin/Views/Management/Accounts.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@model List<Admins>

<div class="">
    <div class="page-header-title">
        <h4 class="page-title">Adminler</h4>
    </div>
</div>
<div class="page-content-wrapper ">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-body">
                        <h4 class="m-b-30 m-t-0"></h4>
                        <div class="row">
                            <form class="form-horizontal" method="post" action="">
                                <div class="col-xs-12">
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>Ad ve Soyad</th>
                                                <th>E-Posta</th>
                                                <th>Oluşturma Tarihi</th>
                                                <th>Durum</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (Admins item in Model)
                                            {
                                                <tr>
                                                    <td>@item.Name @item.Lastname</td>
                                                    <td>@item.Email</td>
                                                    <td>@item.CreatedDate</td>
                                                    <td>
                                                        @if (item.Status == true)
                                                        {
                                                            @Html.Raw("Aktif")
                                                        }
                                                        else
                                                        {
                                                            @Html.Raw("Pasif")
                                                        }
                                                    </td>
                                                    <td><a href="/admin/management/EditAdmin/@item.ID" class="btn btn-sm btn-primary"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a></td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

eticaret/Areas/Admin/Views/Management/AddCategory.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-body">
                <form class="form-horizontal" method="post" action="">
                    <h4 class="m-t-0 m-b-30">Kategori Ekle</h4>
                    <div class="row">
                        @if (ViewBag.Error != null)
                        {
                            <div class="alert alert-danger text-center m-t-10 m-b-10">@ViewBag.Error</div>
                        }
                        <div class="col-md-12">
                            <div class="panel panel-default">
                                <div class="panel-body" style="border: 1px solid #e2e2e2;">
                                    <div class="form-group">
                                        <label class="col-md-2 control-label">Kategori Adı</label>
                                        <div class="col-md-10">
                                            <input name="Name" type="text" spellcheck="false" class="form-control" placeholder="Kategori Adı" value="">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-2 control-label">Ana Kategori</label>
                                        <div class="col-md-10">
                                            <select name="MasterCatID" class="form-control">
                                                <option value="-1">Yok</option>
                                                @{
                                                    eTicaretDBEntities db = new eTicaretDBEntities();
                                                }
                                                @foreach (Categories masterCat in db.Categories.Where(x => x.MasterCatID == null).ToList())
                                                {
                                                    <option value="@masterCat.ID">@masterCat.Name</option>
                                                }
                                            </select>

                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-2 control-label">Kategori Açıklaması</label>
                                        <div class="col-md-10">
                                            <input name="Description" type="text" spellcheck="false" class="form-control" placeholder="Kategori Açıklaması" value="">
                                        </div>
                                    </div>
                                    <button name="submit" type="submit" class="btn btn-success pull-right"><b>Ekle</b></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.ckeditor.com/4.9.2/standard/ckeditor.js"></script>

eticaret/Areas/Admin/Views/Management/GetLogs.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@using PagedList
@using PagedList.Mvc

@model IPagedList<Logs>

<div class="">
    <div class="page-header-title">
        <h4 class="page-title">İşlem Geçmişi</h4>
    </div>
</div>
<div class="page-content-wrapper ">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-body">
                        <h4 class="m-b-30 m-t-0"></h4>
                        <div class="row">
                            <form class="form-horizontal" method="post" action="">
                                <div class="col-xs-12">
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>İşlem</th>
                                                <th>Oluşturma Tarihi</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (Logs item in Model)
                                            {
                                                <tr>
                                                    <td>@item.ID</td>
                                                    <td>@item.Message</td>
                                                    <td>@item.CreatedDate</td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                    @Html.PagedListPager(Model, _pageNo => Url.Action("GetLogs", "Management", new { pageNo = _pageNo }))
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

eticaret/Areas/Admin/Views/Management/Index.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@using PagedList
@using PagedList.Mvc

@model IPagedList<Products>

<div class="">
    <div class="page-header-title">
        <h4 class="page-title">Tüm Ürünler</h4>
    </div>
</div>
<div class="page-content-wrapper ">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <form class="form-inline pull-right">
                    @if (Request.QueryString["arama"] != null)
                    {
                        <a href="/admin/management" class="btn btn-default" style="width:150px;">
                            <i class="fa fa-eraser"></i> Temizle
                        </a>
                    }
                    <input class="form-control" style="width:200px;@if (Request.QueryString["arama"] != null) { @Html.Raw("margin-left:3px;") }" type="text" name="arama" value="@if (Request.QueryString["arama"] != null) {@Html.Raw(Request.QueryString["arama"]) }" placeholder="Arama" />
                    <button class="btn btn-primary" style="margin-left:3px;" type="submit">Ara</button>
                </form>
            </div>
        </div>
        <div class="clearfix m-t-20"></div>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-body">
                        @if (Request.QueryString["Status"] == "DeleteSuccess")
                        {
                            <div class="alert alert-success">Ürün başarıyla silindi.</div>
                        }
                        else if (Request.QueryString["Status"] == "DeleteFailed")
                        {
                            <div class="alert alert-danger">Ürün silinirken hata meydana geldi.</div>
                        }

                        <h4 class="m-b-30 m-t-0"></h4>
                        <div class="row">
                            <div class="col-xs-12">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>Ürün ID</th>
                                            <th>Ürün Adı</th>
                                            <th>Açıklama</th>
                                            <th>Fiyat</th>
                                            <th>Satış Sayısı</th>
                                            <th>Stok Sayısı</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (Products item in Model)
                                        {
                                            <tr>
                                                <td>@item.ID</td>
                                                <td>@item.Name</td>
                                                <td>@item.Description</td>
                                                <td>@string.Format("{0:C}", item.Price)</td>
                                                <td>@item.NumberOfSales</td>
                                                <td>@item.UnitsInStock</td>
                                                <td>
                                                    <a href="/admin/management/EditProduct/@item.ID" class="btn btn-sm btn-primary"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                                    @if (item.Status == true)
                                                    {
                                                        <a data-toggle="modal" data-target="#GeneralDeleteModal" data-id="@item.ID" class="btn btn-sm btn-danger deleteButton"><i class="fa fa-trash" aria-hidden="true"></i></a>
                                                    }
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                                @Html.PagedListPager(Model, _pageNo => Url.Action("Index", "Management", new { pageNo = _pageNo, arama = Request.QueryString["arama"] }))
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> <!-- End Row -->
    </div><!-- container -->
</div>


@Html.DeleteModal("/Admin/management/RemoveProduct", "Ürünü silmek istediğinize emin misiniz?", "Ürün Silinecek!")

eticaret/Areas/Admin/Views/Management/LeftSideBar.cshtml
@{
    Layout = null;
}



<div id="sidebar-menu">
    <ul>
        <li>
            <a href="/Admin/Management/Index" class="waves-effect"><i class="fa fa-list"></i><span> Ürün İşlemleri</span></a>
        </li>
        <li>
            <a href="/Admin/Management/AddProduct" class="waves-effect"><i class="fa fa-plus"></i><span> Ürün Ekle</span></a>
        </li>
        <li>
            <a href="/Admin/Management/AddCategory" class="waves-effect"><i class="fa fa-plus"></i><span> Kategori Ekle</span></a>
        </li>
        <li>
            <a href="/Admin/Management/GetCategories" class="waves-effect"><i class="fa fa-plus"></i><span> Kategori Güncelle</span></a>
        </li>
        <li>
            <a href="/Admin/Management/SoftDeletedProducts" class="waves-effect"><i class="fa fa-low-vision"></i><span> Pasif Ürünleri Gör</span></a>
        </li>
        <li>
            <a href="/Admin/Management/SoldProducts" class="waves-effect"><i class="fa fa-handshake-o"></i><span> Satışları Gör</span></a>
        </li>
        <li>
            <a href="/Admin/Management/Accounts" class="waves-effect"><i class="fa fa-user-o"></i><span> Admin Yönetim</span></a>
        </li>
        <li>
            <a href="/Admin/Management/GetLogs" class="waves-effect"><i class="fa fa-exclamation-triangle"></i><span> İşlem Geçmişi</span></a>
        </li>
    </ul>
</div>

eticaret/Areas/Admin/Views/Management/SoftDeletedProducts.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@using PagedList
@using PagedList.Mvc

@model IPagedList<Products>

<div class="">
    <div class="page-header-title">
        <h4 class="page-title">Tüm Ürünler</h4>
    </div>
</div>
<div class="page-content-wrapper ">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-body">
                        <h4 class="m-b-30 m-t-0"></h4>
                        <div class="row">
                            <div class="col-xs-12">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>Ürün ID</th>
                                            <th>Ürün Adı</th>
                                            <th>Açıklama</th>
                                            <th>Fiyat</th>
                                            <th>Satış Sayısı</th>
                                            <th>Stok Sayısı</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (Products item in Model)
                                        {
                                            <tr>
                                                <td>@item.ID</td>
                                                <td>@item.Name</td>
                                                <td>@item.Description</td>
                                                <td>@string.Format("{0:C}", item.Price)</td>
                                                <td>@item.NumberOfSales</td>
                                                <td>@item.UnitsInStock</td>
                                                <td>
                                                    <a href="/Admin/Management/EditProduct/@item.ID" class="btn btn-sm btn-primary"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                                @Html.PagedListPager(Model, _pageNo => Url.Action("SoftDeletedProducts", "Management", new { pageNo = _pageNo }))
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> <!-- End Row -->
    </div><!-- container -->
</div>

eticaret/Areas/Admin/Views/Management/SoldProducts.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@using PagedList
@using PagedList.Mvc

@model IPagedList<SoldProducts>

<div class="">
    <div class="page-header-title">
        <h4 class="page-title">Satışlar</h4>
    </div>
</div>
<div class="page-content-wrapper ">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-body">
                        <h4 class="m-b-30 m-t-0"></h4>
                        <div class="row">
                            <div class="col-xs-12">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>Ürün Adı</th>
                                            <th>Müşteri Adı</th>
                                            <th>Müşteri Tel. No</th>
                                            <th>Ürün Fiyatı</th>
                                            <th>Satış Tarihi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (SoldProducts item in Model)
                                        {
                                            <tr>
                                                <td>@item.Products.Name</td>
                                                <td>@item.Customers.Fullname</td>
                                                <td>@item.Customers.Phone</td>
                                                <td>@string.Format("{0:C}", item.Products.Price)</td>
                                                <td>@item.Bags.SellDate</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                                @Html.PagedListPager(Model, _pageNo => Url.Action("SoldProducts", "Management", new { pageNo = _pageNo }))
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> <!-- End Row -->
    </div><!-- container -->
</div>